'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddAdminSection

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AddAdminForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddAdminForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UsernameBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UsernameBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UsernameRequiredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UsernameRequiredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''UsernameRegexValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UsernameRegexValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PasswordBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PasswordRequiredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordRequiredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PasswordRegexValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordRegexValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''InsertNewAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InsertNewAdmin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AddAdminButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddAdminButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ViewAdminsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewAdminsButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GoBackButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoBackButton As Global.System.Web.UI.WebControls.Button
End Class
