'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminDashboard

    '''<summary>
    '''AdminUsernameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdminUsernameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TotalUsersLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalUsersLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TotalTasksLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalTasksLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TotalFeedbacksLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalFeedbacksLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LogoutButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoutButton As Global.System.Web.UI.WebControls.LinkButton
End Class
